/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * AccountInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0-SNAPSHOT")
public class AccountInfo {
  public static final String SERIALIZED_NAME_VALIDUNTIL = "validuntil";
  @SerializedName(SERIALIZED_NAME_VALIDUNTIL)
  @javax.annotation.Nonnull
  private Float validuntil;

  public static final String SERIALIZED_NAME_LOGIN = "login";
  @SerializedName(SERIALIZED_NAME_LOGIN)
  @javax.annotation.Nonnull
  private String login;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  @javax.annotation.Nonnull
  private Object options;

  public static final String SERIALIZED_NAME_VALID = "valid";
  @SerializedName(SERIALIZED_NAME_VALID)
  @javax.annotation.Nonnull
  private Boolean valid;

  public static final String SERIALIZED_NAME_TRAFFICLEFT = "trafficleft";
  @SerializedName(SERIALIZED_NAME_TRAFFICLEFT)
  @javax.annotation.Nonnull
  private Long trafficleft;

  public static final String SERIALIZED_NAME_PREMIUM = "premium";
  @SerializedName(SERIALIZED_NAME_PREMIUM)
  @javax.annotation.Nonnull
  private Boolean premium;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public AccountInfo() {
  }

  public AccountInfo validuntil(@javax.annotation.Nonnull Float validuntil) {
    
    this.validuntil = validuntil;
    return this;
  }

  /**
   * Get validuntil
   * @return validuntil
   */
  @javax.annotation.Nonnull

  public Float getValiduntil() {
    return validuntil;
  }


  public void setValiduntil(@javax.annotation.Nonnull Float validuntil) {
    this.validuntil = validuntil;
  }

  public AccountInfo login(@javax.annotation.Nonnull String login) {
    
    this.login = login;
    return this;
  }

  /**
   * Get login
   * @return login
   */
  @javax.annotation.Nonnull

  public String getLogin() {
    return login;
  }


  public void setLogin(@javax.annotation.Nonnull String login) {
    this.login = login;
  }

  public AccountInfo options(@javax.annotation.Nonnull Object options) {
    
    this.options = options;
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @javax.annotation.Nonnull

  public Object getOptions() {
    return options;
  }


  public void setOptions(@javax.annotation.Nonnull Object options) {
    this.options = options;
  }

  public AccountInfo valid(@javax.annotation.Nonnull Boolean valid) {
    
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @javax.annotation.Nonnull

  public Boolean getValid() {
    return valid;
  }


  public void setValid(@javax.annotation.Nonnull Boolean valid) {
    this.valid = valid;
  }

  public AccountInfo trafficleft(@javax.annotation.Nonnull Long trafficleft) {
    
    this.trafficleft = trafficleft;
    return this;
  }

  /**
   * Get trafficleft
   * @return trafficleft
   */
  @javax.annotation.Nonnull

  public Long getTrafficleft() {
    return trafficleft;
  }


  public void setTrafficleft(@javax.annotation.Nonnull Long trafficleft) {
    this.trafficleft = trafficleft;
  }

  public AccountInfo premium(@javax.annotation.Nonnull Boolean premium) {
    
    this.premium = premium;
    return this;
  }

  /**
   * Get premium
   * @return premium
   */
  @javax.annotation.Nonnull

  public Boolean getPremium() {
    return premium;
  }


  public void setPremium(@javax.annotation.Nonnull Boolean premium) {
    this.premium = premium;
  }

  public AccountInfo type(@javax.annotation.Nonnull String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull

  public String getType() {
    return type;
  }


  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountInfo accountInfo = (AccountInfo) o;
    return Objects.equals(this.validuntil, accountInfo.validuntil) &&
        Objects.equals(this.login, accountInfo.login) &&
        Objects.equals(this.options, accountInfo.options) &&
        Objects.equals(this.valid, accountInfo.valid) &&
        Objects.equals(this.trafficleft, accountInfo.trafficleft) &&
        Objects.equals(this.premium, accountInfo.premium) &&
        Objects.equals(this.type, accountInfo.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validuntil, login, options, valid, trafficleft, premium, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountInfo {\n");
    sb.append("    validuntil: ").append(toIndentedString(validuntil)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    trafficleft: ").append(toIndentedString(trafficleft)).append("\n");
    sb.append("    premium: ").append(toIndentedString(premium)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

