/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.pyload.android.openapi.models.Destination;

/**
 * ApiAddPackagePostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0-SNAPSHOT")
public class ApiAddPackagePostRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  @javax.annotation.Nonnull
  private List<String> links = new ArrayList<>();

  public static final String SERIALIZED_NAME_DEST = "dest";
  @SerializedName(SERIALIZED_NAME_DEST)
  @javax.annotation.Nullable
  private Destination dest;

  public ApiAddPackagePostRequest() {
  }

  public ApiAddPackagePostRequest name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * name of the new package
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public ApiAddPackagePostRequest links(@javax.annotation.Nonnull List<String> links) {
    
    this.links = links;
    return this;
  }

  public ApiAddPackagePostRequest addLinksItem(String linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * list of urls
   * @return links
   */
  @javax.annotation.Nonnull

  public List<String> getLinks() {
    return links;
  }


  public void setLinks(@javax.annotation.Nonnull List<String> links) {
    this.links = links;
  }

  public ApiAddPackagePostRequest dest(@javax.annotation.Nullable Destination dest) {
    
    this.dest = dest;
    return this;
  }

  /**
   * &#x60;Destination&#x60;
   * @return dest
   */
  @javax.annotation.Nullable

  public Destination getDest() {
    return dest;
  }


  public void setDest(@javax.annotation.Nullable Destination dest) {
    this.dest = dest;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiAddPackagePostRequest apiAddPackagePostRequest = (ApiAddPackagePostRequest) o;
    return Objects.equals(this.name, apiAddPackagePostRequest.name) &&
        Objects.equals(this.links, apiAddPackagePostRequest.links) &&
        Objects.equals(this.dest, apiAddPackagePostRequest.dest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, links, dest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiAddPackagePostRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    dest: ").append(toIndentedString(dest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

