/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * ApiDeletePackagesPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0-SNAPSHOT")
public class ApiDeletePackagesPostRequest {
  public static final String SERIALIZED_NAME_PACKAGE_IDS = "package_ids";
  @SerializedName(SERIALIZED_NAME_PACKAGE_IDS)
  @javax.annotation.Nonnull
  private List<Integer> packageIds = new ArrayList<>();

  public ApiDeletePackagesPostRequest() {
  }

  public ApiDeletePackagesPostRequest packageIds(@javax.annotation.Nonnull List<Integer> packageIds) {
    
    this.packageIds = packageIds;
    return this;
  }

  public ApiDeletePackagesPostRequest addPackageIdsItem(Integer packageIdsItem) {
    if (this.packageIds == null) {
      this.packageIds = new ArrayList<>();
    }
    this.packageIds.add(packageIdsItem);
    return this;
  }

  /**
   * list of package ids
   * @return packageIds
   */
  @javax.annotation.Nonnull

  public List<Integer> getPackageIds() {
    return packageIds;
  }


  public void setPackageIds(@javax.annotation.Nonnull List<Integer> packageIds) {
    this.packageIds = packageIds;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiDeletePackagesPostRequest apiDeletePackagesPostRequest = (ApiDeletePackagesPostRequest) o;
    return Objects.equals(this.packageIds, apiDeletePackagesPostRequest.packageIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiDeletePackagesPostRequest {\n");
    sb.append("    packageIds: ").append(toIndentedString(packageIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

