/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * ApiIsAuthorizedPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ApiIsAuthorizedPostRequest {
  public static final String SERIALIZED_NAME_FUNC_NAME = "func_name";
  @SerializedName(SERIALIZED_NAME_FUNC_NAME)
  @javax.annotation.Nonnull
  private String funcName;

  public static final String SERIALIZED_NAME_USERDATA = "userdata";
  @SerializedName(SERIALIZED_NAME_USERDATA)
  @javax.annotation.Nonnull
  private Map<String, Object> userdata = new HashMap<>();

  public ApiIsAuthorizedPostRequest() {
  }

  public ApiIsAuthorizedPostRequest funcName(@javax.annotation.Nonnull String funcName) {
    
    this.funcName = funcName;
    return this;
  }

  /**
   * function name
   * @return funcName
   */
  @javax.annotation.Nonnull

  public String getFuncName() {
    return funcName;
  }


  public void setFuncName(@javax.annotation.Nonnull String funcName) {
    this.funcName = funcName;
  }

  public ApiIsAuthorizedPostRequest userdata(@javax.annotation.Nonnull Map<String, Object> userdata) {
    
    this.userdata = userdata;
    return this;
  }

  public ApiIsAuthorizedPostRequest putUserdataItem(String key, Object userdataItem) {
    this.userdata.put(key, userdataItem);
    return this;
  }

  /**
   * dictionary of user data
   * @return userdata
   */
  @javax.annotation.Nonnull

  public Map<String, Object> getUserdata() {
    return userdata;
  }


  public void setUserdata(@javax.annotation.Nonnull Map<String, Object> userdata) {
    this.userdata = userdata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiIsAuthorizedPostRequest apiIsAuthorizedPostRequest = (ApiIsAuthorizedPostRequest) o;
    return Objects.equals(this.funcName, apiIsAuthorizedPostRequest.funcName) &&
        Objects.equals(this.userdata, apiIsAuthorizedPostRequest.userdata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(funcName, userdata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiIsAuthorizedPostRequest {\n");
    sb.append("    funcName: ").append(toIndentedString(funcName)).append("\n");
    sb.append("    userdata: ").append(toIndentedString(userdata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

