/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * ApiParseUrlsPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0-SNAPSHOT")
public class ApiParseUrlsPostRequest {
  public static final String SERIALIZED_NAME_HTML = "html";
  @SerializedName(SERIALIZED_NAME_HTML)
  @javax.annotation.Nullable
  private String html = "null";

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private String url = "null";

  public ApiParseUrlsPostRequest() {
  }

  public ApiParseUrlsPostRequest html(@javax.annotation.Nullable String html) {
    
    this.html = html;
    return this;
  }

  /**
   * html source
   * @return html
   */
  @javax.annotation.Nullable

  public String getHtml() {
    return html;
  }


  public void setHtml(@javax.annotation.Nullable String html) {
    this.html = html;
  }

  public ApiParseUrlsPostRequest url(@javax.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * url to load html source from
   * @return url
   */
  @javax.annotation.Nullable

  public String getUrl() {
    return url;
  }


  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiParseUrlsPostRequest apiParseUrlsPostRequest = (ApiParseUrlsPostRequest) o;
    return Objects.equals(this.html, apiParseUrlsPostRequest.html) &&
        Objects.equals(this.url, apiParseUrlsPostRequest.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(html, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiParseUrlsPostRequest {\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

