/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * ApiStopDownloadsPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-20T06:18:42.159061816Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
public class ApiStopDownloadsPostRequest {
  public static final String SERIALIZED_NAME_FILE_IDS = "file_ids";
  @SerializedName(SERIALIZED_NAME_FILE_IDS)
  @javax.annotation.Nonnull
  private List<Integer> fileIds = new ArrayList<>();

  public ApiStopDownloadsPostRequest() {
  }

  public ApiStopDownloadsPostRequest fileIds(@javax.annotation.Nonnull List<Integer> fileIds) {
    
    this.fileIds = fileIds;
    return this;
  }

  public ApiStopDownloadsPostRequest addFileIdsItem(Integer fileIdsItem) {
    if (this.fileIds == null) {
      this.fileIds = new ArrayList<>();
    }
    this.fileIds.add(fileIdsItem);
    return this;
  }

  /**
   * list of file ids
   * @return fileIds
   */
  @javax.annotation.Nonnull

  public List<Integer> getFileIds() {
    return fileIds;
  }


  public void setFileIds(@javax.annotation.Nonnull List<Integer> fileIds) {
    this.fileIds = fileIds;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiStopDownloadsPostRequest apiStopDownloadsPostRequest = (ApiStopDownloadsPostRequest) o;
    return Objects.equals(this.fileIds, apiStopDownloadsPostRequest.fileIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiStopDownloadsPostRequest {\n");
    sb.append("    fileIds: ").append(toIndentedString(fileIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

