/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * ApiUpdateAccountPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-20T06:18:42.159061816Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
public class ApiUpdateAccountPostRequest {
  public static final String SERIALIZED_NAME_PLUGIN = "plugin";
  @SerializedName(SERIALIZED_NAME_PLUGIN)
  @javax.annotation.Nullable
  private String plugin;

  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  @javax.annotation.Nullable
  private String account;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  @javax.annotation.Nullable
  private String password = "null";

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  @javax.annotation.Nullable
  private Map<String, Object> options = new HashMap<>();

  public ApiUpdateAccountPostRequest() {
  }

  public ApiUpdateAccountPostRequest plugin(@javax.annotation.Nullable String plugin) {
    
    this.plugin = plugin;
    return this;
  }

  /**
   * Get plugin
   * @return plugin
   */
  @javax.annotation.Nullable

  public String getPlugin() {
    return plugin;
  }


  public void setPlugin(@javax.annotation.Nullable String plugin) {
    this.plugin = plugin;
  }

  public ApiUpdateAccountPostRequest account(@javax.annotation.Nullable String account) {
    
    this.account = account;
    return this;
  }

  /**
   * Get account
   * @return account
   */
  @javax.annotation.Nullable

  public String getAccount() {
    return account;
  }


  public void setAccount(@javax.annotation.Nullable String account) {
    this.account = account;
  }

  public ApiUpdateAccountPostRequest password(@javax.annotation.Nullable String password) {
    
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable

  public String getPassword() {
    return password;
  }


  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }

  public ApiUpdateAccountPostRequest options(@javax.annotation.Nullable Map<String, Object> options) {
    
    this.options = options;
    return this;
  }

  public ApiUpdateAccountPostRequest putOptionsItem(String key, Object optionsItem) {
    if (this.options == null) {
      this.options = new HashMap<>();
    }
    this.options.put(key, optionsItem);
    return this;
  }

  /**
   * Get options
   * @return options
   */
  @javax.annotation.Nullable

  public Map<String, Object> getOptions() {
    return options;
  }


  public void setOptions(@javax.annotation.Nullable Map<String, Object> options) {
    this.options = options;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiUpdateAccountPostRequest apiUpdateAccountPostRequest = (ApiUpdateAccountPostRequest) o;
    return Objects.equals(this.plugin, apiUpdateAccountPostRequest.plugin) &&
        Objects.equals(this.account, apiUpdateAccountPostRequest.account) &&
        Objects.equals(this.password, apiUpdateAccountPostRequest.password) &&
        Objects.equals(this.options, apiUpdateAccountPostRequest.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plugin, account, password, options);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiUpdateAccountPostRequest {\n");
    sb.append("    plugin: ").append(toIndentedString(plugin)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

